// Wortlisten für Klassen 1-4 (Nomen, Verben, Adjektive und andere Wortarten)
const WORD_LISTS = {
    1: [
        'Antwort', 'Apfel', 'Arzt', 'Ast', 'Auto', 'Bauer', 'Baum', 'Berg', 'Blatt', 'Blume',
        'Brief', 'Brot', 'Brücke', 'Buch', 'Bus', 'Bäcker', 'Dach', 'Decke', 'Dorf', 'Eis',
        'Erde', 'Ernte', 'Feld', 'Fenster', 'Feuer', 'Flugzeug', 'Fluss', 'Garage', 'Garten', 'Geschichte',
        'Hafen', 'Haus', 'Idee', 'Jahr', 'Karte', 'Kirche', 'Kissen', 'Kiste', 'Käse', 'Lampe',
        'Lösung', 'Markt', 'Milch', 'Minute', 'Mond', 'Nachricht', 'Paket', 'Park', 'Plan', 'Platz',
        'Polizist', 'Projekt', 'Radio', 'Regen', 'Reise', 'Saft', 'Samen', 'Schnee', 'Schüler', 'Segel',
        'Sonne', 'Spiel', 'Stadt', 'Stern', 'Strand', 'Straße', 'Stuhl', 'Tag', 'Tal', 'Telefon',
        'Teppich', 'Turm', 'Uhr', 'Vergangenheit', 'Wald', 'Wasser', 'Werkstatt', 'Wind', 'Wolke', 'Wurzel',
        'Zeitung', 'Zug', 'alt', 'antworten', 'arbeiten', 'beginnen', 'beschreiben', 'bitter', 'blau', 'bleiben',
        'braten', 'bringen', 'drehen', 'dunkel', 'durstig', 'ernst', 'ernten', 'erzählen', 'fahren', 'fangen',
        'fest', 'finden', 'forschen', 'freundlich', 'frieren', 'fröhlich', 'geduldig', 'gehen', 'gelb', 'genau',
        'geschlossen', 'gesund', 'glatt', 'golden', 'graben', 'groß', 'grün', 'halten', 'heben', 'hell',
        'hoch', 'holen', 'jung', 'kaufen', 'klettern', 'kochen', 'krank', 'kurz', 'kühl', 'lachen',
        'landen', 'lang', 'laufen', 'legen', 'leicht', 'lernen', 'lesen', 'locker', 'mutig', 'müde',
        'neu', 'ordnen', 'pflanzen', 'planen', 'prüfen', 'putzen', 'rau', 'reisen', 'rennen', 'reparieren',
        'rot', 'salzig', 'schieben', 'schmelzen', 'schreiben', 'schwer', 'selten', 'setzen', 'silbern', 'spielen',
        'springen', 'starten', 'stoppen', 'suchen', 'süß', 'tanzen', 'tauchen', 'tragen', 'trocken', 'täglich',
        'ungeduldig', 'untersuchen', 'vergleichen', 'verkaufen', 'verstehen', 'versuchen', 'voll', 'wach', 'warm', 'waschen',
        'weinen', 'weiß', 'zeichnen', 'ziehen', 'zählen', 'ändern', 'ängstlich', 'öffnen', 'üben'
    ],
    2: [
        'Abenteuer', 'Antwort', 'Apfel', 'Arzt', 'Ast', 'Aufgabe', 'Auto', 'Ball', 'Bauer', 'Baum',
        'Berg', 'Bild', 'Blatt', 'Blume', 'Boot', 'Brief', 'Brot', 'Brücke', 'Buch', 'Bus',
        'Bäcker', 'Computer', 'Dach', 'Decke', 'Dorf', 'Eis', 'Erde', 'Ernte', 'Fahrrad', 'Feld',
        'Fenster', 'Feuer', 'Feuerwehr', 'Flugzeug', 'Fluss', 'Frage', 'Freund', 'Garage', 'Garten', 'Geschichte',
        'Hafen', 'Haus', 'Heft', 'Hund', 'Idee', 'Insel', 'Jahr', 'Karte', 'Katze', 'Keller',
        'Kind', 'Kirche', 'Kissen', 'Kiste', 'Koch', 'Käse', 'Lampe', 'Lehrer', 'Lösung', 'Markt',
        'Milch', 'Minute', 'Monat', 'Mond', 'Nachricht', 'Paket', 'Park', 'Pause', 'Plan', 'Platz',
        'Polizist', 'Post', 'Projekt', 'Radio', 'Regen', 'Reise', 'Saft', 'Samen', 'Sand', 'Schnee',
        'Schrank', 'Schule', 'Schüler', 'See', 'Segel', 'Sonne', 'Spiel', 'Stadt', 'Stern', 'Stift',
        'Strand', 'Straße', 'Stuhl', 'Stunde', 'Tag', 'Tal', 'Telefon', 'Teppich', 'Tisch', 'Turm',
        'Tür', 'Uhr', 'Urlaub', 'Vergangenheit', 'Wald', 'Wasser', 'Welle', 'Werkstatt', 'Wiese', 'Wind',
        'Woche', 'Wolke', 'Wurzel', 'Zeitung', 'Zug', 'Zukunft', 'alt', 'antworten', 'arbeiten', 'backen',
        'bauen', 'beginnen', 'beobachten', 'bewegen', 'bitter', 'blau', 'bleiben', 'braten', 'braun', 'breit',
        'bringen', 'bunt', 'denken', 'drehen', 'dunkel', 'durstig', 'eckig', 'enden', 'entdecken', 'erfinden',
        'erklären', 'ernst', 'ernten', 'erzählen', 'fahren', 'fallen', 'fangen', 'faul', 'fest', 'finden',
        'fleißig', 'fliegen', 'forschen', 'fragen', 'frei', 'freundlich', 'frieren', 'fröhlich', 'geben', 'geduldig',
        'gehen', 'gelb', 'genau', 'geschlossen', 'gestalten', 'gesund', 'gießen', 'glatt', 'golden', 'graben',
        'groß', 'grün', 'halten', 'hart', 'heben', 'heiß', 'helfen', 'hell', 'hoch', 'holen',
        'hungrig', 'hören', 'jung', 'jährlich', 'kalt', 'kaufen', 'klar', 'klein', 'klettern', 'kochen',
        'krank', 'kurz', 'kühl', 'lachen', 'landen', 'lang', 'langsam', 'langweilig', 'laufen', 'laut',
        'leer', 'legen', 'leicht', 'leise', 'lernen', 'locker', 'lustig', 'malen', 'messen', 'mutig',
        'müde', 'nass', 'nehmen', 'neu', 'nützlich', 'offen', 'ordnen', 'pflanzen', 'planen', 'praktisch',
        'prüfen', 'putzen', 'rau', 'rechnen', 'reisen', 'rennen', 'reparieren', 'retten', 'rollen', 'rot',
        'rufen', 'ruhig', 'rund', 'salzig', 'sammeln', 'sauber', 'sauer', 'schieben', 'schließen', 'schmal',
        'schmutzig', 'schreiben', 'schwach', 'schwarz', 'schwer', 'schwimmen', 'sehen', 'selten', 'setzen', 'silbern',
        'singen', 'spannend', 'spielen', 'sprechen', 'springen', 'stark', 'starten', 'steigen', 'stellen', 'stoppen',
        'süß', 'tanzen', 'tauchen', 'teilen', 'tief', 'tragen', 'traurig', 'trüb', 'täglich', 'ungeduldig',
        'untersuchen', 'vergleichen', 'verkaufen', 'verstehen', 'versuchen', 'voll', 'wach', 'warm', 'waschen', 'weich',
        'weinen', 'weiß', 'werfen', 'wichtig', 'wild', 'zeichnen', 'ziehen', 'zählen', 'ändern', 'ängstlich',
        'öffnen', 'üben'
    ],
    3: [
        'Abenteuer', 'Antwort', 'Apfel', 'Arzt', 'Ast', 'Aufgabe', 'Auto', 'Ball', 'Bauer', 'Baum',
        'Berg', 'Bild', 'Blatt', 'Blume', 'Boot', 'Brief', 'Brot', 'Brücke', 'Buch', 'Bus',
        'Bäcker', 'Computer', 'Dach', 'Decke', 'Dorf', 'Eis', 'Erde', 'Ernte', 'Fahrrad', 'Feld',
        'Fenster', 'Feuer', 'Feuerwehr', 'Flugzeug', 'Fluss', 'Frage', 'Freund', 'Garage', 'Garten', 'Geschichte',
        'Hafen', 'Haus', 'Heft', 'Hund', 'Idee', 'Insel', 'Jahr', 'Karte', 'Katze', 'Keller',
        'Kind', 'Kirche', 'Kissen', 'Kiste', 'Koch', 'Käse', 'Lampe', 'Lehrer', 'Lösung', 'Markt',
        'Milch', 'Minute', 'Monat', 'Mond', 'Nachricht', 'Paket', 'Park', 'Pause', 'Plan', 'Platz',
        'Polizist', 'Post', 'Projekt', 'Radio', 'Regen', 'Reise', 'Saft', 'Samen', 'Sand', 'Schnee',
        'Schrank', 'Schule', 'Schüler', 'See', 'Segel', 'Sonne', 'Spiel', 'Stadt', 'Stern', 'Stift',
        'Strand', 'Straße', 'Stuhl', 'Stunde', 'Tag', 'Tal', 'Telefon', 'Teppich', 'Tisch', 'Turm',
        'Tür', 'Uhr', 'Urlaub', 'Vergangenheit', 'Wald', 'Wasser', 'Welle', 'Werkstatt', 'Wiese', 'Wind',
        'Woche', 'Wolke', 'Wurzel', 'Zeitung', 'Zug', 'Zukunft', 'alt', 'antworten', 'arbeiten', 'backen',
        'bauen', 'beginnen', 'beobachten', 'beschreiben', 'bewegen', 'bitter', 'blau', 'bleiben', 'braten', 'braun',
        'breit', 'bringen', 'bunt', 'denken', 'drehen', 'drücken', 'dunkel', 'durstig', 'eckig', 'enden',
        'entdecken', 'erfinden', 'erklären', 'ernst', 'ernten', 'erzählen', 'fahren', 'fallen', 'fangen', 'faul',
        'fest', 'finden', 'fleißig', 'fliegen', 'forschen', 'fragen', 'frei', 'freundlich', 'frieren', 'fröhlich',
        'geben', 'geduldig', 'gehen', 'gelb', 'genau', 'geschlossen', 'gestalten', 'gesund', 'gießen', 'glatt',
        'golden', 'graben', 'groß', 'grün', 'halten', 'hart', 'heben', 'heiß', 'helfen', 'hell',
        'hoch', 'holen', 'hungrig', 'häufig', 'hören', 'jung', 'jährlich', 'kalt', 'kaufen', 'klar',
        'klein', 'klettern', 'kochen', 'krank', 'kurz', 'kühl', 'lachen', 'landen', 'lang', 'langsam',
        'langweilig', 'laufen', 'laut', 'leer', 'legen', 'leicht', 'leise', 'lernen', 'lesen', 'locker',
        'lustig', 'malen', 'messen', 'mutig', 'müde', 'nass', 'nehmen', 'neu', 'nützlich', 'offen',
        'ordnen', 'pflanzen', 'planen', 'praktisch', 'prüfen', 'putzen', 'rau', 'rechnen', 'reisen', 'rennen',
        'reparieren', 'retten', 'rollen', 'rot', 'rufen', 'ruhig', 'rund', 'salzig', 'sammeln', 'sauber',
        'sauer', 'schieben', 'schließen', 'schmal', 'schmelzen', 'schmutzig', 'schnell', 'schreiben', 'schwach', 'schwarz',
        'schwer', 'schwimmen', 'sehen', 'selten', 'setzen', 'silbern', 'singen', 'sortieren', 'spannend', 'spielen',
        'sprechen', 'springen', 'stark', 'starten', 'steigen', 'stellen', 'stoppen', 'suchen', 'süß', 'tanzen',
        'tauchen', 'teilen', 'tief', 'tragen', 'traurig', 'trocken', 'trüb', 'täglich', 'ungeduldig', 'untersuchen',
        'vergleichen', 'verkaufen', 'verstehen', 'versuchen', 'voll', 'wach', 'warm', 'waschen', 'weich', 'weinen',
        'weiß', 'werfen', 'wichtig', 'wild', 'zeichnen', 'ziehen', 'zählen', 'ändern', 'ängstlich', 'öffnen',
        'üben'
    ],
    4: [
        'Abenteuer', 'Antwort', 'Apfel', 'Arzt', 'Ast', 'Aufgabe', 'Auto', 'Ball', 'Bauer', 'Baum',
        'Berg', 'Bild', 'Blatt', 'Blume', 'Boot', 'Brief', 'Brot', 'Brücke', 'Buch', 'Bus',
        'Bäcker', 'Computer', 'Dach', 'Decke', 'Dorf', 'Eis', 'Erde', 'Ernte', 'Fahrrad', 'Feld',
        'Fenster', 'Feuer', 'Feuerwehr', 'Flugzeug', 'Fluss', 'Frage', 'Freund', 'Garage', 'Garten', 'Geschichte',
        'Hafen', 'Haus', 'Heft', 'Hund', 'Idee', 'Insel', 'Jahr', 'Karte', 'Katze', 'Keller',
        'Kind', 'Kirche', 'Kissen', 'Kiste', 'Koch', 'Käse', 'Lampe', 'Lehrer', 'Lösung', 'Markt',
        'Milch', 'Minute', 'Monat', 'Mond', 'Nachricht', 'Paket', 'Park', 'Pause', 'Plan', 'Platz',
        'Polizist', 'Post', 'Projekt', 'Radio', 'Regen', 'Reise', 'Saft', 'Samen', 'Sand', 'Schnee',
        'Schrank', 'Schule', 'Schüler', 'See', 'Segel', 'Sonne', 'Spiel', 'Stadt', 'Stern', 'Stift',
        'Strand', 'Straße', 'Stuhl', 'Stunde', 'Tag', 'Tal', 'Telefon', 'Teppich', 'Tisch', 'Turm',
        'Tür', 'Uhr', 'Urlaub', 'Vergangenheit', 'Wald', 'Wasser', 'Welle', 'Werkstatt', 'Wiese', 'Wind',
        'Woche', 'Wolke', 'Wurzel', 'Zeitung', 'Zug', 'Zukunft', 'alt', 'antworten', 'arbeiten', 'backen',
        'bauen', 'beginnen', 'beobachten', 'beschreiben', 'bewegen', 'bitter', 'blau', 'bleiben', 'braten', 'braun',
        'breit', 'bringen', 'bunt', 'denken', 'drehen', 'drücken', 'dunkel', 'durstig', 'eckig', 'enden',
        'entdecken', 'erfinden', 'erklären', 'ernst', 'ernten', 'erzählen', 'fahren', 'fallen', 'fangen', 'faul',
        'fest', 'finden', 'fleißig', 'fliegen', 'forschen', 'fragen', 'frei', 'freundlich', 'frieren', 'fröhlich',
        'geben', 'geduldig', 'gehen', 'gelb', 'genau', 'geschlossen', 'gestalten', 'gesund', 'gießen', 'glatt',
        'golden', 'graben', 'groß', 'grün', 'halten', 'hart', 'heben', 'heiß', 'helfen', 'hell',
        'hoch', 'holen', 'hungrig', 'häufig', 'hören', 'jung', 'jährlich', 'kalt', 'kaufen', 'klar',
        'klein', 'klettern', 'kochen', 'krank', 'kurz', 'kühl', 'lachen', 'landen', 'lang', 'langsam',
        'langweilig', 'laufen', 'laut', 'leer', 'legen', 'leicht', 'leise', 'lernen', 'lesen', 'locker',
        'lustig', 'malen', 'messen', 'mutig', 'müde', 'nass', 'nehmen', 'neu', 'nützlich', 'offen',
        'ordnen', 'pflanzen', 'planen', 'praktisch', 'prüfen', 'putzen', 'rau', 'rechnen', 'reisen', 'rennen',
        'reparieren', 'retten', 'rollen', 'rot', 'rufen', 'ruhig', 'rund', 'salzig', 'sammeln', 'sauber',
        'sauer', 'schieben', 'schließen', 'schmal', 'schmelzen', 'schmutzig', 'schnell', 'schreiben', 'schwach', 'schwarz',
        'schwer', 'schwimmen', 'sehen', 'selten', 'setzen', 'silbern', 'singen', 'sortieren', 'spannend', 'spielen',
        'sprechen', 'springen', 'stark', 'starten', 'steigen', 'stellen', 'stoppen', 'suchen', 'süß', 'tanzen',
        'tauchen', 'teilen', 'tief', 'tragen', 'traurig', 'trocken', 'trüb', 'täglich', 'ungeduldig', 'untersuchen',
        'vergleichen', 'verkaufen', 'verstehen', 'versuchen', 'voll', 'wach', 'warm', 'waschen', 'weich', 'weinen',
        'weiß', 'werfen', 'wichtig', 'wild', 'zeichnen', 'ziehen', 'zählen', 'ändern', 'ängstlich', 'öffnen',
        'üben'
    ]
};
